apiVersion: v1
kind: Route
metadata:
  name: wso2ei-pattern1-integrator-route-gw
spec:
  to:
    kind: Service
    name: wso2ei-pattern1-integrator-gateway-service
    weight: 100
  port:
    targetPort: pass-through-https
  tls:
    termination: passthrough